import { invoke } from "@tauri-apps/api/core";
import type {
  AppStats,
  Book,
  BookInput,
  Category,
  Chapter,
  ChapterKind,
  ChapterInput,
  ClipboardItem,
  Note,
  Tag,
  TaskItem,
} from "./types";

export const api = {
  listNotes: () => invoke<Note[]>("list_notes"),
  listArchived: () => invoke<Note[]>("list_archived"),
  listTrashed: () => invoke<Note[]>("list_trashed"),
  listFavorites: () => invoke<Note[]>("list_favorites"),
  listTasks: () => invoke<TaskItem[]>("list_tasks"),
  notesByCategory: (id: number) => invoke<Note[]>("notes_by_category", { categoryId: id }),
  notesByTag: (id: number) => invoke<Note[]>("notes_by_tag", { tagId: id }),
  search: (q: string) => invoke<Note[]>("search_notes", { query: q }),
  getNote: (id: number) => invoke<Note | null>("get_note", { id }),
  createNote: (title: string, content: string, categoryId?: number | null) =>
    invoke<Note>("create_note", { title, content, categoryId }),
  updateNote: (id: number, title: string, content: string, categoryId?: number | null) =>
    invoke<void>("update_note", { id, title, content, categoryId }),
  setNoteCategory: (id: number, categoryId: number | null) =>
    invoke<void>("set_note_category", { id, categoryId }),
  togglePin: (id: number) => invoke<void>("toggle_pin", { id }),
  toggleFavorite: (id: number) => invoke<void>("toggle_favorite", { id }),
  toggleArchive: (id: number) => invoke<void>("toggle_archive", { id }),
  trashNote: (id: number) => invoke<void>("trash_note", { id }),
  restoreNote: (id: number) => invoke<void>("restore_note", { id }),
  deleteForever: (id: number) => invoke<void>("delete_note_forever", { id }),
  emptyTrash: () => invoke<void>("empty_trash"),

  listBooks: () => invoke<Book[]>("list_books"),
  getBook: (id: number) => invoke<Book | null>("get_book", { id }),
  createBook: (book: BookInput) =>
    invoke<Book>("create_book", {
      title: book.title,
      subtitle: book.subtitle,
      author: book.author,
      description: book.description,
      genre: book.genre,
      status: book.status,
      trimSize: book.trimSize,
      fontFamily: book.fontFamily,
      fontSize: book.fontSize,
      lineHeight: book.lineHeight,
      paragraphSpacing: book.paragraphSpacing,
      margin: book.margin,
      wordGoal: book.wordGoal ?? 50000,
      coverColor: book.coverColor ?? "#a56b3e",
      dedication: book.dedication ?? "",
      epigraph: book.epigraph ?? "",
      copyrightText: book.copyrightText ?? "",
      acknowledgements: book.acknowledgements ?? "",
      tocEnabled: book.tocEnabled ?? true,
      tocTitle: book.tocTitle ?? "Contents",
      tocDepth: book.tocDepth ?? 3,
      tocIncludeFrontMatter: book.tocIncludeFrontMatter ?? false,
      tocIncludeBackMatter: book.tocIncludeBackMatter ?? false,
      layoutJson: book.layoutJson ?? "{}",
    }),
  updateBook: (id: number, book: BookInput) =>
    invoke<void>("update_book", {
      id,
      title: book.title,
      subtitle: book.subtitle,
      author: book.author,
      description: book.description,
      genre: book.genre,
      status: book.status,
      trimSize: book.trimSize,
      fontFamily: book.fontFamily,
      fontSize: book.fontSize,
      lineHeight: book.lineHeight,
      paragraphSpacing: book.paragraphSpacing,
      margin: book.margin,
      wordGoal: book.wordGoal ?? 50000,
      coverColor: book.coverColor ?? "#a56b3e",
      dedication: book.dedication ?? "",
      epigraph: book.epigraph ?? "",
      copyrightText: book.copyrightText ?? "",
      acknowledgements: book.acknowledgements ?? "",
      tocEnabled: book.tocEnabled ?? true,
      tocTitle: book.tocTitle ?? "Contents",
      tocDepth: book.tocDepth ?? 3,
      tocIncludeFrontMatter: book.tocIncludeFrontMatter ?? false,
      tocIncludeBackMatter: book.tocIncludeBackMatter ?? false,
      layoutJson: book.layoutJson ?? "{}",
    }),
  deleteBook: (id: number) => invoke<void>("delete_book", { id }),
  listChapters: (bookId: number) => invoke<Chapter[]>("list_chapters", { bookId }),
  createChapter: (bookId: number, chapter: ChapterInput) =>
    invoke<Chapter>("create_chapter", {
      bookId,
      chapterKind: chapter.chapterKind ?? "chapter",
      title: chapter.title,
      content: chapter.content,
      position: chapter.position,
      tocInclude: chapter.tocInclude ?? true,
      tocHeadingExclusions: chapter.tocHeadingExclusions ?? [],
    }),
  updateChapter: (id: number, title: string, content: string, chapterKind: ChapterKind = "chapter", tocInclude = true, tocHeadingExclusions: string[] = []) =>
    invoke<void>("update_chapter", { id, chapterKind, title, content, tocInclude, tocHeadingExclusions }),
  deleteChapter: (id: number) => invoke<void>("delete_chapter", { id }),
  reorderChapters: (bookId: number, chapterIds: number[]) =>
    invoke<void>("reorder_chapters", { bookId, chapterIds }),

  listCategories: () => invoke<Category[]>("list_categories"),
  createCategory: (name: string, color: string, icon: string) =>
    invoke<number>("create_category", { name, color, icon }),
  updateCategory: (id: number, name: string, color: string, icon: string) =>
    invoke<void>("update_category", { id, name, color, icon }),
  deleteCategory: (id: number) => invoke<void>("delete_category", { id }),

  listTags: () => invoke<Tag[]>("list_tags"),
  createTag: (name: string, color: string) => invoke<number>("create_tag", { name, color }),
  deleteTag: (id: number) => invoke<void>("delete_tag", { id }),
  setNoteTags: (noteId: number, tagIds: number[]) =>
    invoke<void>("set_note_tags", { noteId, tagIds }),

  listClipboard: (limit = 100) => invoke<ClipboardItem[]>("list_clipboard_items", { limit }),
  saveClipboard: (content: string) => invoke<number>("save_clipboard_item", { content }),
  deleteClipboardItem: (id: number) => invoke<void>("delete_clipboard_item", { id }),
  clearClipboard: () => invoke<void>("clear_clipboard_history"),

  getSetting: (key: string) => invoke<string | null>("get_setting", { key }),
  setSetting: (key: string, value: string) => invoke<void>("set_setting", { key, value }),
  stats: () => invoke<AppStats>("app_stats"),
  saveAttachment: (data: number[], ext: string) =>
    invoke<string>("save_attachment", { data, ext }),
};
